# Generated by Django 5.0.7 on 2024-07-27 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_category_slug"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
