# Generated by Django 5.0.7 on 2024-08-04 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_reviewratings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReviewRatings",
            new_name="ReviewRating",
        ),
    ]
