# Generated by Django 5.0.7 on 2024-08-04 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_rename_reviewratings_reviewrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewrating",
            old_name="ratings",
            new_name="rating",
        ),
    ]
