# Generated by Django 5.0.7 on 2024-08-04 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "product_gallery",
                "verbose_name_plural": "product_gallery",
            },
        ),
    ]
